### ISSUE TITLE
Error when adding new site (nitro apply)

### ISSUE THREAD

**Issue by dhmax88** [craftcms/nitro#144]
When trying to mount a new folder / site I keep getting this error:

```
umount failed: The following errors occurred:
"=>" is not mounted
"=>" not found in database
```

I'm not sure where these arrow functions are coming from...

Using 1.0.0-beta.3

**Comment by jasonmccallister** [comment]
Hi @dhmax88, I have seen this a few times. Can you run the following commands and provide the output?

1. `nitro context`
2. `nitro info`

That should give me a good indicator of whats happening.

**Comment by dhmax88** [comment]
Hi @jasonmccallister 

I destroyed and re-initialised the box, which seems to have resolved the issue for now. It seems to happen when the box has been stopped/paused and then restarted – so I'll report back when / if it happens again.

Current results of your commands:

1. `nitro context`
```
Using config: /Users/david/.nitro/nitro-dev.yaml
------
php: "7.4"
mounts:
  - source: ~/Sites/MUD/OMCT
    dest: /home/ubuntu/sites/local.omct.com
  - source: ~/Sites/DUET/MMC Ventures
    dest: /home/ubuntu/sites/local.mmc.com
databases:
  - engine: mysql
    version: "5.7"
    port: "3306"
sites:
  - hostname: local.omct.com
    webroot: /home/ubuntu/sites/local.omct.com/deploy/public
  - hostname: local.mmc.com
    webroot: /home/ubuntu/sites/local.mmc.com/deploy/public
```

2. `nitro info`
```
Name:           nitro-dev
State:          Running
IPv4:           192.168.64.3
Release:        Ubuntu 18.04.4 LTS
Image hash:     3b2e3aaaebf2 (Ubuntu 18.04 LTS)
Load:           0.08 0.26 0.28
Disk usage:     4.5G out of 38.6G
Memory usage:   660.9M out of 3.9G
Mounts:         /Users/david/Sites/MUD/OMCT          => /home/ubuntu/sites/local.omct.com
                    UID map: 501:default
                    GID map: 20:default
                /Users/david/Sites/DUET/MMC Ventures => /home/ubuntu/sites/local.mmc.com
                    UID map: 501:default
                    GID map: 20:default
```

**Comment by jasonmccallister** [comment]
@dhmax88 ahh ok, I have to give credit to @lukeholder for this one. There is an issue with multipass removing mounts during macOS sleep (https://github.com/canonical/multipass/issues/1531). 

If this happens again, you can run `nitro restart` and it should resolve itself!

**Comment by dhmax88** [comment]
I don't think this issue is resolve.

I've tried `nitro restart` but still getting the error... output below:

```
Webroot for "local.omct.com" matches
Webroot for "local.mmc.com" matches
Webroot for "local.omct-next.com" does not match, found "/etc/nginx/sites-available/local.omct-next.com"
Removing mount /Users/david/Sites/DUET/MMC from nitro-dev
Mounting ~/Sites/DUET/MMC Ventures to nitro-dev
Mounting ~/Sites/MUD/OMCT-NEXT to nitro-dev
Adding site local.omct-next.com to nitro-dev
umount failed: The following errors occurred:
"=>" is not mounted
"=>" not found in database
Error: exit status 2
```

```
php: "7.4"
mounts:
  - source: ~/Sites/MUD/OMCT
    dest: /home/ubuntu/sites/local.omct.com
  - source: ~/Sites/DUET/MMC Ventures
    dest: /home/ubuntu/sites/local.mmc.com
  - source: ~/Sites/MUD/OMCT-NEXT
    dest: /home/ubuntu/sites/local.omct-next.com
databases:
  - engine: mysql
    version: "5.7"
    port: "3306"
sites:
  - hostname: local.omct.com
    webroot: /home/ubuntu/sites/local.omct.com/deploy/public
  - hostname: local.mmc.com
    webroot: /home/ubuntu/sites/local.mmc.com/deploy/public
  - hostname: local.omct-next.com
    webroot: /home/ubuntu/sites/local.omct-next.com/public
```

```
Name:           nitro-dev
State:          Running
IPv4:           192.168.64.3
Release:        Ubuntu 18.04.4 LTS
Image hash:     3b2e3aaaebf2 (Ubuntu 18.04 LTS)
Load:           0.85 0.52 0.21
Disk usage:     4.5G out of 38.6G
Memory usage:   355.6M out of 3.9G
Mounts:         /Users/david/Sites/MUD/OMCT          => /home/ubuntu/sites/local.omct.com
                    UID map: 501:default
                    GID map: 20:default
                /Users/david/Sites/DUET/MMC Ventures => /home/ubuntu/sites/local.mmc.com
                    UID map: 501:default
                    GID map: 20:default
```
