### ISSUE TITLE
PHP not using ENV ini values?

### ISSUE THREAD

**Issue by michaelroper** [craftcms/nitro#268]
### Description

So today I hit the stupid `max_input_vars` error when saving a matrix field. Now, the error message mentioned I'd hit the limit of _2000_, but I know that the default nitro setting is 5000, but if I look on the `/admin/utilities/php-info` page, I see this:

> **Core**
> `max_input_vars = 2000`
> 
> **Environment**
> `PHP_MAX_INPUT_VARS = 5000`
> 
> **PHP Variables**
> `$_SERVER['PHP_MAX_INPUT_VARS'] = 5000`
> `$_ENV['PHP_MAX_INPUT_VARS'] = 5000`

Why might it be using the `2000` value, and not the `5000`?

I tried the same with the `memory_limit` value, by using `nitro iniset` to set it to 768M and found the same issue.

> **Core**
> `memory_limit = 512M`
> 
> **Environment**
> `PHP_MEMORY_LIMIT = 768M`
> 
> **PHP Variables**
> `$_SERVER['PHP_MEMORY_LIMIT'] = 768M`
> `$_ENV['PHP_MEMORY_LIMIT'] = 768M`

All values seem correct in `nitro.yaml`, and i have made sure everything is up to date by `brew upgrade nitro` and `nitro update`, and stopped docker, trashed all the containers and images, restarted docker, then did `nitro apply` to pull fresh images and rebuild the containers - still no change.

### Additional info

```
Nitro CLI:       2.0.2
Nitro gRPC:      2.0.2
Docker API:      1.41 (1.12 min)
Docker CLI:      1.41
--
PHP:             7.4.15 (and 8.0)
Postgres:        13
Craft:           3.6.7
```

**Comment by jasonmccallister** [comment]
@michaelroper does your nitro.yaml have the memory provided on your site? Under sites.site.php.setting?

**Comment by michaelroper** [comment]
@jasonmccallister it has the 768M value that was put there by `nitro iniset`
```yaml
sites:
    - hostname: voc-www-cms.test
      path: ~/Sites/voc-www-cms
      version: "7.4"
      php:
        displayerrors: false
        maxexecutiontime: 0
        maxinputvars: 6000
        maxinputtime: 0
        maxfileupload: ""
        memorylimit: 768M
        opcacheenable: false
        opcacherevalidatefreq: 0
        postmaxsize: ""
        uploadmaxfilesize: ""
      webroot: web
      xdebug: false
      blackfire: false
```

**Comment by jasonmccallister** [comment]
I see what's happening, I'll get a fix out this morning. Sorry about that!

**Comment by jasonmccallister** [comment]
@michaelroper just tagged 2.0.3 that fixes this issue. 

If you can remove the `php` settings manually from your `nitro.yaml` file and after upgrading run `nitro upgrade` then `nitro iniset` you should have values that are using `_` between the names (e.g. `display_errors`) and the settings you have not modified should not longer be there.

The build takes around 5 minutes to complete. That should resolve the issue but let me know if it does not!

**Comment by michaelroper** [comment]
aha! i did notice the lack of underscores when i looked at the yaml, but figured they were just mapped through, because the env vars were correct... 

thanks for the quick fix! confirmed that it does work... though a small confession - at first I thought it didn't work, because the value was still the same... and then I realised I had a .user.ini file in the web folder (for settings on heroku).. and the nitro server was actually respecting the values in that file. 🤦

**Comment by jasonmccallister** [comment]
That is such a happy coincidence... we planned on adding that support in the future but did not realize that it was already working so... 🎉
